# Site settings
title: Occillo
email: chewy509@mailcity.com
description: >
  Occillo, a breakout style arcade game
baseurl: "" 
url: "https://dkartaschew.github.io/occillo/"
github_username:  dkartaschew

# Build settings
markdown: kramdown
kramdown:
  input: GFM